
# base image
FROM tomcat:8.5

# MAINTAINER
MAINTAINER qingshenlwy@163.com

# put zip file into directory
ADD CompanyNews.war /usr/local/tomcat/webapps/

# put zip file into directory
ADD ROOT/ /usr/local/tomcat/webapps/ROOT/
